/**
 * ZeroHour – human-readable explanations from detected failures.
 */

import { DetectedFailure } from '../types';

export function failureScenario(f: DetectedFailure): string {
  const scenarios: Record<string, string> = {
    A1: 'An attacker or bug sends invalid input to the API; it reaches business logic and causes a crash or corrupt state.',
    A2: 'Client validation is bypassed; malformed or malicious payloads hit the backend and break assumptions.',
    A3: 'User-controlled numbers overflow, become NaN, or go negative; calculations or quotas fail.',
    A4: 'Large offset or unbounded list is requested; memory or CPU spikes and the service degrades or crashes.',
    A5: 'An exception is thrown; the empty catch hides it and the process continues in an invalid state.',
    A6: 'A client is modified or the API is called directly; business rules are bypassed (e.g. price, eligibility).',
    A7: 'A sensitive feature is enabled on the client without server check; inconsistent or insecure behavior.',
    B1: 'An unauthenticated request hits a protected route; data or actions are exposed.',
    B2: 'Secrets are read from code or config; credentials are compromised (repo, build, or runtime).',
    B3: 'A non-admin or non-owner calls admin/payment endpoint; privilege escalation or unauthorized charges.',
    B4: 'Repeated requests to an expensive endpoint exhaust CPU, memory, or downstream; service becomes unavailable.',
    B5: 'A malicious or oversized file is uploaded; storage or execution is abused.',
    B6: 'A user changes an ID in the request and accesses or modifies another user’s resource (IDOR).',
    C1: 'An awaited call rejects; the error propagates and is unhandled; process may crash.',
    C2: 'A promise rejects; without .catch(), unhandledRejection is emitted and the process can exit.',
    C3: 'A remote service hangs; the request never completes and connections or event loop block.',
    C4: 'A failing dependency is retried indefinitely; load and failure cascade.',
    C5: 'An uncaught error in a request handler crashes the server or leaks stack traces.',
    C6: 'A promise rejects and no handler runs; Node may terminate.',
    D1: 'One of several writes fails; the database is left in an inconsistent state.',
    D2: 'An update partially applies; on failure there is no rollback and state is inconsistent.',
    D3: 'A write fails; the error is not handled and state or process is left inconsistent.',
    D4: 'Duplicate values are inserted for a “unique” field; integrity and business logic break.',
    D5: 'Two requests update the same counter or balance; one update is lost (race condition).',
    E1: 'The API fails; the UI stays in loading state and the user sees no error.',
    E2: 'The request fails; the app does not show an error and the user is left confused.',
    E3: 'The server rejects the action; the UI already showed success and is now wrong.',
    E4: 'The user double-clicks submit; two requests are sent and duplicate records or charges occur.',
    E5: 'The API returns 4xx/5xx; the client treats it as success and shows wrong data or flow.',
    F1: 'The service is reachable from the network; attack surface is larger than intended.',
    F2: 'Debug or dev mode runs in production; info leaks or performance degrades.',
    F3: 'Sensitive cookies or data are sent over HTTP; they can be intercepted.',
    F4: 'Production uses the same config as dev; secrets or behavior are wrong.',
    F5: 'Secrets in the repo are pushed or forked; credentials are exposed.',
  };
  return scenarios[f.ruleId] ?? 'This pattern can lead to failure under load, abuse, or invalid input.';
}

export function fixNowBullets(f: DetectedFailure): string[] {
  const fixes: Record<string, string[]> = {
    A1: ['Add server-side validation (schema/zod/joi) for all request body, params, and query.', 'Reject invalid input with 400 before business logic.'],
    A2: ['Implement the same validation on the backend as on the client.', 'Never trust client-side checks for security or integrity.'],
    A3: ['Validate and bound numeric input (min, max, type).', 'Use safe arithmetic or bigint where overflow is possible.'],
    A4: ['Enforce a maximum limit and default for list/offset parameters.', 'Validate range before querying.'],
    A5: ['Log the error in catch blocks.', 'Re-throw or return a controlled error response instead of swallowing.'],
    A6: ['Move business rules (price, eligibility, permissions) to the backend.', 'Use frontend only for UX, not enforcement.'],
    A7: ['Enforce feature flags on the server.', 'Gate sensitive features by server-side checks.'],
    B1: ['Add authentication middleware to all protected routes.', 'Return 401 for unauthenticated requests.'],
    B2: ['Remove secrets from source; use env vars or a secret manager.', 'Add the file to .gitignore and rotate any exposed credentials.'],
    B3: ['Add authorization checks (role, ownership) on admin and payment routes.', 'Return 403 when the user is not allowed.'],
    B4: ['Add rate limiting (per IP or per user) on expensive endpoints.', 'Return 429 when limit is exceeded.'],
    B5: ['Validate file type (allowlist) and size before processing.', 'Store uploads outside web root and scan if needed.'],
    B6: ['Verify resource ownership or permission before returning or updating.', 'Use session/user context, not only request IDs.'],
    C1: ['Wrap async handlers in try/catch and handle errors.', 'Return a safe response or re-throw to a global handler.'],
    C2: ['Add .catch() to every promise chain.', 'Or use async/await with try/catch.'],
    C3: ['Set a timeout on all HTTP/client requests.', 'Use AbortController or library timeout option.'],
    C4: ['Add circuit breaker or max retries with backoff.', 'Fail fast when dependency is down.'],
    C5: ['Register a global error middleware (e.g. 4-arg (err, req, res, next)).', 'Log and return a generic 500 without stack to clients.'],
    C6: ['Add .catch() or try/catch for all promise-returning code.', 'Ensure no unhandled rejections.'],
    D1: ['Wrap multi-step writes in a transaction.', 'Commit only when all steps succeed; rollback on error.'],
    D2: ['Use a transaction for partial updates or implement explicit rollback.', 'On failure, revert or compensate.'],
    D3: ['Wrap DB writes in try/catch and handle errors.', 'Return a clear error and do not leave state half-updated.'],
    D4: ['Add a unique constraint or index on the field in the DB/schema.', 'Handle duplicate key errors in code.'],
    D5: ['Use a transaction or “select for update” for counter/balance updates.', 'Serialize concurrent updates.'],
    E1: ['Add error state and UI (message, retry) when the request fails.', 'Use an ErrorBoundary for React.'],
    E2: ['Handle fetch/axios errors and show a user-visible message.', 'Use .catch() or isError and render error UI.'],
    E3: ['On API failure, revert optimistic update and show error.', 'Use onError/onSettled to reset state.'],
    E4: ['Disable the submit button while the request is in flight.', 'Optionally debounce submit to avoid double clicks.'],
    E5: ['Check response.ok or response.status before using the body.', 'Handle 4xx/5xx with error UI or retry.'],
    F1: ['Bind to 127.0.0.1 or a specific interface unless you need external access.', 'Use a reverse proxy for public exposure.'],
    F2: ['Disable debug in production; use NODE_ENV or env-specific config.', 'Never enable debug in prod.'],
    F3: ['Use HTTPS in production and set secure cookie flags.', 'Redirect HTTP to HTTPS.'],
    F4: ['Split config by NODE_ENV or env name.', 'Load only the config for the current environment.'],
    F5: ['Remove secrets from the repo; use env or secret manager.', 'Add .env to .gitignore and rotate exposed secrets.'],
  };
  return fixes[f.ruleId] ?? ['Review this code path and add validation, error handling, or guards as appropriate.'];
}

/** Risk Story Mode: 3-step "how this failure becomes an incident" */
export function riskStorySteps(f: DetectedFailure): [string, string, string] {
  const stories: Record<string, [string, string, string]> = {
    A1: ['Invalid or malicious input hits the API with no validation.', 'Request reaches business logic; bad data triggers a crash or corrupts state.', 'Service fails or data is corrupted; users or downstream systems are affected.'],
    A2: ['Client-side checks are bypassed (e.g. devtools, direct API call).', 'Backend trusts the request; malformed or forged data enters the system.', 'Business logic or data integrity breaks; revenue or policy is violated.'],
    A3: ['User supplies a number that overflows, is NaN, or negative.', 'Arithmetic runs without bounds; result is wrong or throws.', 'Wrong totals, quotas, or pricing; financial or operational incident.'],
    A4: ['A large offset or unbounded list is requested.', 'Query or loop runs without limit; memory or CPU spikes.', 'Service degrades or OOMs; availability incident.'],
    A5: ['An exception is thrown in the try block.', 'Catch block is empty; error is swallowed and execution continues.', 'Process runs in invalid state; data or behavior is wrong; hard to debug.'],
    A6: ['User or attacker bypasses frontend (e.g. calls API, edits client).', 'Server has no equivalent rule; request is accepted.', 'Wrong price, eligibility, or access; revenue or compliance incident.'],
    A7: ['Feature flag is toggled only on the client.', 'Server does not enforce; sensitive feature can be enabled client-side.', 'Inconsistent or insecure behavior in production.'],
    B1: ['Request is sent to a protected route without auth.', 'No middleware checks identity; handler runs for anyone.', 'Data or actions are exposed; confidentiality or integrity incident.'],
    B2: ['Secrets are read from code or config (repo, build, or runtime).', 'Credentials are exposed via version control, logs, or build artifacts.', 'Account or system compromise; abuse of third-party services.'],
    B3: ['Non-admin or non-owner calls admin/payment endpoint.', 'No authorization check; request is processed.', 'Privilege escalation or unauthorized payment; compliance incident.'],
    B4: ['Repeated requests hit an expensive endpoint.', 'No rate limit; CPU, memory, or downstream is exhausted.', 'Service becomes unavailable; DoS incident.'],
    B5: ['Malicious or oversized file is uploaded.', 'No type/size validation; file is stored or processed.', 'Storage abuse, code execution, or crash; security or availability incident.'],
    B6: ['User changes resource ID in the request (e.g. /users/123 → 456).', 'Server returns or updates by ID without ownership check.', 'Another user’s data is read or modified (IDOR); compliance incident.'],
    C1: ['An awaited call rejects (e.g. DB, API).', 'No try/catch; rejection propagates as unhandled.', 'Process may crash or leave state inconsistent; availability incident.'],
    C2: ['A promise rejects (e.g. network failure).', 'No .catch(); unhandledRejection is emitted.', 'Node may exit; availability incident.'],
    C3: ['Remote service hangs or is very slow.', 'Request has no timeout; connection or event loop blocks.', 'Thread pool or connections exhausted; cascade failure.'],
    C4: ['Dependency is down; retries keep firing.', 'No circuit breaker; every request retries and adds load.', 'Cascade failure; dependent service is overwhelmed.'],
    C5: ['An error is thrown in a request handler.', 'No global error handler; Express/Node crashes or leaks stack.', 'Server restarts or stack trace is exposed; availability or security.'],
    C6: ['A promise rejects and no handler runs.', 'unhandledRejection is emitted.', 'Process may terminate; availability incident.'],
    D1: ['First write succeeds; second write fails.', 'No transaction; partial state is committed.', 'Database is inconsistent; business logic or reports are wrong.'],
    D2: ['Update runs; mid-way an error occurs.', 'No rollback or transaction; state is partially updated.', 'Data inconsistency; wrong balances or counts.'],
    D3: ['A DB write fails (constraint, connection, etc.).', 'Error is not caught; caller does not handle.', 'Half-updated state or crash; integrity or availability.'],
    D4: ['Duplicate value is inserted for a “unique” field.', 'No unique constraint; duplicate is stored.', 'Integrity and business logic break; duplicates in reports.'],
    D5: ['Two requests read–modify–write the same counter/balance.', 'No lock or transaction; one update overwrites the other.', 'Lost update; wrong total or balance; financial error.'],
    E1: ['API call fails (network, 5xx).', 'No error UI; loading state never clears.', 'User sees infinite loader; support burden and perceived outage.'],
    E2: ['Request fails; no .catch() or error UI.', 'User sees no feedback.', 'Confusion and support tickets; perceived broken feature.'],
    E3: ['Optimistic update is shown; server then rejects.', 'No rollback; UI stays “success”.', 'User believes action succeeded; data is inconsistent.'],
    E4: ['User double-clicks submit.', 'Two requests are sent; no disable or debounce.', 'Duplicate order or charge; revenue or data incident.'],
    E5: ['API returns 4xx/5xx.', 'Client does not check status; treats body as success.', 'Wrong data shown or wrong flow; user or business error.'],
    F1: ['Service listens on 0.0.0.0.', 'Process is reachable from the network.', 'Larger attack surface; unintended exposure.'],
    F2: ['Debug or dev mode is enabled in production.', 'Verbose logs or dev tools are active.', 'Info leak or performance degradation.'],
    F3: ['Cookies or data sent over HTTP.', 'Traffic is not encrypted.', 'Session or data intercepted; confidentiality incident.'],
    F4: ['Same config used in all environments.', 'Prod may get dev secrets or behavior.', 'Wrong config in prod; security or correctness.'],
    F5: ['Secrets are committed to the repo.', 'Code is pushed or forked.', 'Credentials exposed; compromise.'],
  };
  return stories[f.ruleId] ?? [
    'A precondition or invariant is violated.',
    'The failure propagates through the system.',
    'Business impact: availability, integrity, or confidentiality is affected.',
  ];
}

/** Blast Radius: text-based visualization of what is affected */
export function blastRadiusText(f: DetectedFailure): string {
  const radii: Record<string, string> = {
    A1: 'API layer → business logic → data/service',
    A2: 'Client → API → backend state',
    A3: 'User input → calculation path → totals/quotas',
    A4: 'API/query → memory/CPU → entire process',
    A5: 'Failing code path → silent continue → process state',
    A6: 'Frontend → API (bypassed) → revenue/policy',
    A7: 'Client feature flag → server (no check) → behavior',
    B1: 'Public network → route handler → all users’ data',
    B2: 'Repo/build/runtime → credentials → all linked services',
    B3: 'Caller → admin/payment route → privileges or money',
    B4: 'Attacker/load → expensive endpoint → CPU/memory/downstream',
    B5: 'Upload → storage/processing → server or storage',
    B6: 'Request (any user) → resource by ID → any user’s data',
    C1: 'Async call → unhandled rejection → process',
    C2: 'Promise → unhandledRejection → process',
    C3: 'Network call → hang → connections/event loop',
    C4: 'Dependency → retries → dependent service',
    C5: 'Request handler → uncaught error → server response',
    C6: 'Promise → no handler → process',
    D1: 'Multi-step write → partial commit → database',
    D2: 'Update → partial apply → table/row',
    D3: 'Write → unhandled error → DB/process',
    D4: 'Insert → no constraint → table integrity',
    D5: 'Concurrent writes → race → counter/balance',
    E1: 'API failure → loading state → all users of that UI',
    E2: 'Request failure → no UI → user session',
    E3: 'Server reject → optimistic UI → user view',
    E4: 'Double submit → two requests → order/payment',
    E5: '4xx/5xx → client ignores → user flow',
    F1: 'Process → 0.0.0.0 → network',
    F2: 'Config → debug flag → logs/behavior',
    F3: 'Client → HTTP → cookies/data',
    F4: 'Config file → env → all environments',
    F5: 'Repo → push/fork → credentials',
  };
  return radii[f.ruleId] ?? 'Code path → failure → system impact';
}

export function failureTitle(f: DetectedFailure): string {
  const titles: Record<string, string> = {
    A1: 'Missing input validation on public API',
    A2: 'Trusting client-side validation only',
    A3: 'Arithmetic on user input without bounds',
    A4: 'Missing boundary checks',
    A5: 'Silent failures (empty catch)',
    A6: 'Business rules only in frontend',
    A7: 'Client-side feature flags only',
    B1: 'Missing authentication middleware',
    B2: 'Hardcoded or plaintext secrets',
    B3: 'Missing authorization on admin/payment routes',
    B4: 'No rate limiting on expensive endpoints',
    B5: 'File uploads without validation',
    B6: 'Direct object access without ownership check',
    C1: 'Async without try/catch',
    C2: 'Promises without .catch()',
    C3: 'Network calls without timeouts',
    C4: 'Retries without circuit breakers',
    C5: 'Missing global error handler',
    C6: 'Unhandled promise rejections',
    D1: 'Multi-step DB writes without transactions',
    D2: 'Partial updates without rollback',
    D3: 'DB writes without error handling',
    D4: 'Missing uniqueness/integrity constraints',
    D5: 'Concurrent writes without guards',
    E1: 'Infinite loaders without error UI',
    E2: 'API failures hidden from users',
    E3: 'Optimistic UI without rollback',
    E4: 'Forms without debounce/disable',
    E5: 'Blind trust in backend success',
    F1: 'Services exposed on 0.0.0.0',
    F2: 'Debug enabled in production',
    F3: 'Missing HTTPS/secure flags',
    F4: 'Missing env-specific configs',
    F5: 'Secrets committed to repo',
  };
  return titles[f.ruleId] ?? `Rule ${f.ruleId}: ${f.detectionExplanation}`;
}
