import os
import subprocess
import sys
import time

def run_script(script_name):
    """Runs a python script and returns True if successful, False otherwise."""
    print(f"\n{'='*50}")
    print(f"Running {script_name}...")
    print(f"{'='*50}\n")
    
    try:
        # Using sys.executable to ensure we use the same python interpreter
        result = subprocess.run([sys.executable, script_name], check=True)
        return result.returncode == 0
    except subprocess.CalledProcessError as e:
        print(f"\n[ERROR] {script_name} failed with exit code {e.returncode}")
        return False
    except FileNotFoundError:
        print(f"\n[ERROR] Script {script_name} not found.")
        return False

def main():
    # Step 1: Run the RAG Workflow to generate recommendations
    rag_script = "process_alert_workflow.py"
    if not run_script(rag_script):
        print("\n[STOP] Pipeline halted due to error in RAG step.")
        return

    # Check if output file was created
    output_file = "final_recommendation.json"
    if not os.path.exists(output_file):
        print(f"\n[ERROR] {output_file} was not generated by {rag_script}.")
        print("[STOP] Pipeline halted.")
        return
        
    print(f"\n[SUCCESS] {rag_script} completed. Output found at {output_file}.")
    
    # Step 2: Run the Machine Explainer
    # Pause briefly for readability
    time.sleep(1)
    
    explainer_script = "machine_explainer.py"
    if not run_script(explainer_script):
        print("\n[STOP] Pipeline halted due to error in Explainer step.")
        return

    print(f"\n{'='*50}")
    print("Full Pipeline Completed Successfully")
    print(f"{'='*50}\n")

if __name__ == "__main__":
    main()
